name: "book-store"
services:
  catalog-db:
    image: postgres:16-alpine
    container_name: calaog-db
    environment:
      - POSTGRES_USER=same
      - POSTGRES_PASSWORD=same
      - POSTGRES_DB=same
    ports:
      - "3001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  order-db:
    image: postgres:16-alpine
    container_name: orders-db
    environment:
      - POSTGRES_USER=same
      - POSTGRES_PASSWORD=same
      - POSTGRES_DB=orders
    ports:
      - "3002:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  bookstore-rabbitmq:
    image: rabbitmq:3.12.11-management
    container_name: bookstore-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=same
      - RABBITMQ_DEFAULT_PASS=same
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memeory: 500m
