name: "book-store"
services:
  catalog-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=same
      - POSTGRES_PASSWORD=same
      - POSTGRES_DB=same
    ports:
      - "3001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m